service: soat-lambda

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  signup:
    handler: dist/functions/anonymous-login.handler
    events:
      - http:
          path: anonymous-login
          method: post
  login:
    handler: dist/functions/signup-and-login.handler
    events:
      - http:
          path: signup-and-login
          method: post
